---

R1:
  hostname: "192.168.2.1"
  username: "cisco"
  password: "cisco"
  groups:
    - cisco_group
R2:
  hostname: "192.168.2.2"
  username: "cisco"
  password: "cisco"
  groups:
    - cisco_group
