---
rtr:
  name: CE2
  platform: xe
  lo:  
    - { name: Loopback0,
        description: Configured by Ansible,
        ip: 10.100.100.6,
        mask: 255.255.255.0,
        ospf_area: 2 }
  gis:
    - { name: GigabitEthernet3,
        description: Link to PE2-1,
        ip: 10.100.26.2,
        mask: 255.255.255.252,
        ospf_area: 2 }
    - { name: GigabitEthernet4,
        description: Link to PE2-2,
        ip: 10.100.46.2,
        mask: 255.255.255.252,
        ospf_area: 2 }
