---
rtr:
  name: PE1-1
  platform: xr
  lo:  
    - { name: Loopback0,
        description: Configured by Ansible,
        ip: 10.100.100.1,
        mask: 255.255.255.0,
        ospf_area: 0 }
  gis:
    - { name: GigabitEthernet0/0/0/0,
        description: Link to PE2-1,
        ip: 10.100.12.1,
        mask: 255.255.255.252,
        ospf_area: 0 }
    - { name: GigabitEthernet0/0/0/1,
        description: Link to PE2-2,
        ip: 10.100.14.1,
        mask: 255.255.255.252,
        ospf_area: 0 }
    - { name: GigabitEthernet0/0/0/2,
        description: Link to PE1-2,
        ip: 10.100.13.1,
        mask: 255.255.255.252,
        ospf_area: 1 }
    - { name: GigabitEthernet0/0/0/3,
        description: Link to CE1,
        ip: 10.100.15.1,
        mask: 255.255.255.252,
        ospf_area: 1 }
