---
rtr:
  name: PE2-2
  platform: ios
  lo: { name: Loopback0, ip: 10.100.100.4, mask: 255.255.255.0, description: Configured by Ansible }
  gis:
    - { name: GigabitEthernet1, ip: 10.100.34.2, mask: 255.255.255.252, description: Link to PE1-2}
    - { name: GigabitEthernet2, ip: 10.100.14.2, mask: 255.255.255.252, description: Link to PE1-1}
    - { name: GigabitEthernet3, ip: 10.100.24.2, mask: 255.255.255.252, description: Link to PE2-1}
    - { name: GigabitEthernet4, ip: 10.100.46.1, mask: 255.255.255.252, description: Link to CE2}
