---
rtr:
  name: PE2-2
  platform: xe
  lo:  
    - { name: Loopback0,
        description: Configured by Ansible,
        ip: 10.100.100.4,
        mask: 255.255.255.0,
        ospf_area: 0 }
  gis:
    - { name: GigabitEthernet1,
        description: Link to PE1-2,
        ip: 10.100.34.2,
        mask: 255.255.255.252,
        ospf_area: 0 }
    - { name: GigabitEthernet2,
        description: Link to PE1-1,
        ip: 10.100.14.2,
        mask: 255.255.255.252,
        ospf_area: 0 }
    - { name: GigabitEthernet3,
        description: Link to PE2-1,
        ip: 10.100.24.2,
        mask: 255.255.255.252,
        ospf_area: 2 }
    - { name: GigabitEthernet4,
        description: Link to CE2,
        ip: 10.100.46.1,
        mask: 255.255.255.252,
        ospf_area: 2 }
