---

- name: "LACP Config"
  hosts: all
  connection: network_cli

  tasks:
    - name: "Send LACP Config"
      cisco.iosxr.iosxr_config:
        src: "../../ansible_templates/iosxr_delete_lacp.jinja"

