---

- name: "IOS-XR LACP Config"
  hosts: ios_xr
  connection: network_cli

  tasks:
    - name: "Send LACP Config"
      cisco.iosxr.iosxr_config:
        src: "../../cli-templates/iosxr_create_lacp.jinja"

- name: "IOS-XE LACP Config"
  hosts: ios_xe
  connection: network_cli

  tasks:
    - name: "Send LACP Config"
      cisco.ios.ios_config:
        src: "../../cli-templates/iosxe_create_lacp.jinja"

